_BASE_: "../Base-RCNN-FPN.yaml"
# NUM_GPUS : 1
DATASETS:
  TRAIN: ('camo_train_novel1_3shot',)
  TEST: ('camo_test_novel1',)
MODEL:
  ROI_HEADS:
    NUM_CLASSES:
  WEIGHTS:
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (1600,)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0