services:
  mmlab_danhnt_fs:
    image: mmlab_danhnt_fs
    container_name: mmlab_danhnt_fs
    build:
      context: .
      dockerfile: Dockerfile
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    volumes:
      - ./share_folder:/share_folder
      - /home/:/home/
      - /storageStudents/:/storageStudents/
      - /mnt/mmlab2024nas/:/mnt/mmlab2024nas/
      - /mmlabworkspace/:/mmlabworkspace/
      - /mmlabworkspace_new/:/mmlabworkspace_new/
      - /mnt/mmlabworkspace/:/mnt/mmlabworkspace/
    ipc: host
    network_mode: host
    tty: true
    stdin_open: true
