_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_base/model_reset_remove.pth"
  MASK_ON: True
  BOX_IOU_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    LOSS_TYPE: 'focal'
    COMBINE_TYPE: 'sigmoid'
    OUTPUT_LAYER: "BoxUncertaintyFastRCNNOutputLayers"
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('camo_train_novel1_3shot',)
  TEST: ('camo_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0025
  STEPS: (10000,)
  MAX_ITER: 1000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/coco/mask_rcnn/mask_rcnn_R_50_FPN_ft_novel_1shot_sigmoid_classifier_box_iou_uncertainty"