_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: 
  MASK_ON: True
  BOX_IOU_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 47
    FREEZE_FEAT: True
    LOSS_TYPE: 'focal'
    COMBINE_TYPE: 'sigmoid'
    OUTPUT_LAYER: "BoxUncertaintyBayesianOutputLayers"
    COSINE_SCALE: 1.5
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('camo_train_novel1_2shot',)
  TEST: ('camo_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.005
  STEPS: (10000,)
  MAX_ITER: 2500
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/camo/mask_rcnn/mask_rcnn_R_101_FPN_ft_sigmoid_classifier_box_iou_uncertainty_bayesian_novel_2shot"