_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: 
  MASK_ON: True
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 47
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('camo_train_novel1_3shot',)
  TEST: ('camo_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.00125
  STEPS: (10000,)
  MAX_ITER: 1500
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/camo/mask_rcnn/mask_rcnn_R_50_FPN_ft_novel_1shot"