_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS:
  MASK_ON: True
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 47
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('camo_train_novel1_2shot',)
  TEST: ('camo_test_novel1',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (1200, 2400,)
  MAX_ITER: 1500
  CHECKPOINT_PERIOD: 100000
  WARMUP_ITERS: 0
OUTPUT_DIR: "checkpoints/camo/mask_rcnn/mask_rcnn_R_101_FPN_ft_novel_1shot"